name: CI/CD

on:
  push:
    branches: [ 'main' ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
  
      with: 
        fetch-depth: 0
        path: .

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run ESLint
      working-directory: ./frontend
      run: npm run lint --if-present

    - name: Run tests
      working-directory: ./frontend
      run: npm run test

      
    - name: Install shared dependencies
      working-directory: ./shared
      run: npm install

    - name: Build shared types
      working-directory: ./shared
      run: npx tsc


      
    - name: Build project
      working-directory: ./frontend
      run: npm run build

