name: CI/CD

on:
  push:
    branches: [ 'main' ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint --if-present

    - name: Build project
      run: npm run build

    - name: Check .next existence
      run: |
        echo "Contents of root directory:"
        ls -la
        echo "Contents of .next directory:"
        ls -la .next || echo ".next folder not found"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: .next

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build
        path: .next


    - name:  Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      run: netlify deploy --dir=.next --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEBSITE_ID }}
